development: &default
  adapter:  postgresql
  database: gerbera_development
  username: postgres
  encoding: unicode
  host: db
  password: postgres_password

test:
  <<: *default
  database: gerbera_test
